'use strict';
const A4_W=210,A4_H=297,PPM=3,OUT_W=Math.round(A4_W*PPM),OUT_H=Math.round(A4_H*PPM);
const REF=[{name:'linksboven',x:15,y:15},{name:'rechtsboven',x:195,y:15},{name:'rechtsonder',x:195,y:282},{name:'linksonder',x:15,y:282}];
const FIELD=100,FX0=(A4_W-FIELD)/2,FY0=(A4_H-FIELD)/2,FX1=FX0+FIELD,FY1=FY0+FIELD;
const $=id=>document.getElementById(id),input=$('photoInput'),pc=$('photoCanvas'),rc=$('resultCanvas');
const pctx=pc.getContext('2d',{willReadFrequently:true}),rctx=rc.getContext('2d',{willReadFrequently:true});let sourceImage=null,points=[],analysis=null;
input.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const bmp=await createImageBitmap(f),s=Math.min(1,1800/Math.max(bmp.width,bmp.height));pc.width=Math.round(bmp.width*s);pc.height=Math.round(bmp.height*s);pctx.drawImage(bmp,0,0,pc.width,pc.height);sourceImage=pctx.getImageData(0,0,pc.width,pc.height);points=[];$('calibrationCard').hidden=false;$('resultCard').hidden=true;updateCalibration();$('calibrationCard').scrollIntoView({behavior:'smooth'})});
function canvasXY(ev){const r=pc.getBoundingClientRect();return{x:(ev.clientX-r.left)*pc.width/r.width,y:(ev.clientY-r.top)*pc.height/r.height}}
pc.addEventListener('pointerdown',ev=>{if(!sourceImage||points.length>=4)return;points.push(canvasXY(ev));updateCalibration()});$('undoBtn').onclick=()=>{points.pop();updateCalibration()};$('resetBtn').onclick=()=>{points=[];updateCalibration()};
function updateCalibration(){if(sourceImage)pctx.putImageData(sourceImage,0,0);pctx.lineWidth=Math.max(2,pc.width/500);pctx.font=`${Math.max(16,pc.width/35)}px system-ui`;points.forEach((p,i)=>{pctx.beginPath();pctx.arc(p.x,p.y,10,0,Math.PI*2);pctx.strokeStyle='#ff2d2d';pctx.stroke();pctx.fillStyle='#ff2d2d';pctx.fillText(String(i+1),p.x+13,p.y-10);if(i>0){pctx.beginPath();pctx.moveTo(points[i-1].x,points[i-1].y);pctx.lineTo(p.x,p.y);pctx.stroke()}});const n=points.length;$('tapInstruction').textContent=n<4?`${n+1}/4 - ${REF[n].name}`:'4/4 - kalibratiepunten compleet';$('analyzeBtn').disabled=n!==4}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let m=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[m][k]))m=i;[M[k],M[m]]=[M[m],M[k]];if(Math.abs(M[k][k])<1e-12)throw new Error('Kalibratie is geometrisch instabiel.');const d=M[k][k];for(let j=k;j<=n;j++)M[k][j]/=d;for(let i=0;i<n;i++)if(i!==k){const q=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=q*M[k][j]}}return M.map(r=>r[n])}
function homography(dst,src){const A=[],b=[];for(let i=0;i<4;i++){const x=dst[i].x,y=dst[i].y,u=src[i].x,v=src[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}return[...solve(A,b),1]}
function mapH(h,x,y){const d=h[6]*x+h[7]*y+h[8];return{x:(h[0]*x+h[1]*y+h[2])/d,y:(h[3]*x+h[4]*y+h[5])/d}}
function sampleBilinear(data,w,h,x,y){if(x<0||y<0||x>=w-1||y>=h-1)return[255,255,255,255];const x0=Math.floor(x),y0=Math.floor(y),dx=x-x0,dy=y-y0,out=[0,0,0,255];for(let c=0;c<3;c++){const i00=(y0*w+x0)*4+c,i10=i00+4,i01=i00+w*4,i11=i01+4;out[c]=data[i00]*(1-dx)*(1-dy)+data[i10]*dx*(1-dy)+data[i01]*(1-dx)*dy+data[i11]*dx*dy}return out}
function rectify(){const dst=REF.map(p=>({x:p.x*PPM,y:p.y*PPM})),h=homography(dst,points),out=new ImageData(OUT_W,OUT_H),sd=sourceImage.data;for(let y=0;y<OUT_H;y++)for(let x=0;x<OUT_W;x++){const s=mapH(h,x,y),rgba=sampleBilinear(sd,sourceImage.width,sourceImage.height,s.x,s.y),i=(y*OUT_W+x)*4;out.data[i]=rgba[0];out.data[i+1]=rgba[1];out.data[i+2]=rgba[2];out.data[i+3]=255}return out}
function grayAt(d,i){return .2126*d[i]+.7152*d[i+1]+.0722*d[i+2]}function smooth(a,r=8){const out=new Float32Array(a.length),p=new Float64Array(a.length+1);for(let i=0;i<a.length;i++)p[i+1]=p[i]+a[i];for(let i=0;i<a.length;i++){const lo=Math.max(0,i-r),hi=Math.min(a.length,i+r+1);out[i]=(p[hi]-p[lo])/(hi-lo)}return out}
function profile(img,axis,x0,y0,x1,y1){const d=img.data,w=img.width;if(axis==='x'){const a=new Float32Array(x1-x0);for(let x=x0;x<x1;x++){let v=[];for(let y=y0;y<y1;y+=3)v.push(grayAt(d,(y*w+x)*4));v.sort((a,b)=>a-b);a[x-x0]=v[Math.floor(v.length/2)]}return smooth(a)}const a=new Float32Array(y1-y0);for(let y=y0;y<y1;y++){let v=[];for(let x=x0;x<x1;x+=3)v.push(grayAt(d,(y*w+x)*4));v.sort((a,b)=>a-b);a[y-y0]=v[Math.floor(v.length/2)]}return smooth(a)}
function derivative(a){const d=new Float32Array(a.length);for(let i=1;i<a.length-1;i++)d[i]=(a[i+1]-a[i-1])/2;return d}function peakAbs(d,e,s){let lo=Math.max(1,Math.round(e-s)),hi=Math.min(d.length-2,Math.round(e+s)),best=lo,bv=-1;for(let i=lo;i<=hi;i++){const v=Math.abs(d[i]);if(v>bv){bv=v;best=i}}return{idx:best,strength:bv}}
function analyzeRect(img){const m=25,x0=Math.round((FX0-m)*PPM),x1=Math.round((FX1+m)*PPM),y0=Math.round((FY0-m)*PPM),y1=Math.round((FY1+m)*PPM),cp=derivative(profile(img,'x',x0,y0,x1,y1)),rp=derivative(profile(img,'y',x0,y0,x1,y1)),s=30*PPM,L=peakAbs(cp,m*PPM,s),R=peakAbs(cp,(m+100)*PPM,s),T=peakAbs(rp,m*PPM,s),B=peakAbs(rp,(m+100)*PPM,s),Xl=x0+L.idx,Xr=x0+R.idx,Yt=y0+T.idx,Yb=y0+B.idx,width=(Xr-Xl)/PPM,height=(Yb-Yt)/PPM;if(width<60||width>140||height<60||height>140)throw new Error(`Onwaarschijnlijke veldmaat gevonden (${width.toFixed(1)} x ${height.toFixed(1)} mm). Controleer de foto en kalibratie.`);return{width,height,left:Xl/PPM-FX0,right:Xr/PPM-FX1,top:Yt/PPM-FY0,bottom:Yb/PPM-FY1,cx:(Xl+Xr)/(2*PPM)-A4_W/2,cy:(Yt+Yb)/(2*PPM)-A4_H/2,bounds:[Xl,Yt,Xr,Yb]}}
$('analyzeBtn').onclick=()=>{try{const rect=rectify();rc.width=OUT_W;rc.height=OUT_H;rctx.putImageData(rect,0,0);analysis=analyzeRect(rect);drawOverlay();showResult();$('resultCard').hidden=false;$('resultCard').scrollIntoView({behavior:'smooth'})}catch(e){alert('Analyse mislukt: '+e.message)}};
function drawOverlay(){const[xl,yt,xr,yb]=analysis.bounds;rctx.lineWidth=3;rctx.strokeStyle='#222';rctx.strokeRect(FX0*PPM,FY0*PPM,100*PPM,100*PPM);rctx.strokeStyle='#ff2424';rctx.strokeRect(xl,yt,xr-xl,yb-yt);rctx.strokeStyle='#1769ff';rctx.beginPath();rctx.moveTo(OUT_W/2-18,OUT_H/2);rctx.lineTo(OUT_W/2+18,OUT_H/2);rctx.moveTo(OUT_W/2,OUT_H/2-18);rctx.lineTo(OUT_W/2,OUT_H/2+18);rctx.stroke()}
function mm(v){return`${v>=0?'+':''}${v.toFixed(2)} mm`}function showResult(){$('widthOut').textContent=analysis.width.toFixed(2)+' mm';$('heightOut').textContent=analysis.height.toFixed(2)+' mm';$('leftOut').textContent=mm(analysis.left);$('rightOut').textContent=mm(analysis.right);$('topOut').textContent=mm(analysis.top);$('bottomOut').textContent=mm(analysis.bottom);$('cxOut').textContent=mm(analysis.cx);$('cyOut').textContent=mm(analysis.cy);updateBadge()}
function updateBadge(){if(!analysis)return;const t=parseFloat($('tolerance').value),bad=[analysis.left,analysis.right,analysis.top,analysis.bottom].some(v=>Math.abs(v)>t),b=$('statusBadge');b.textContent=bad?'BUITEN INGESTELDE TOLERANTIE':'BINNEN INGESTELDE TOLERANTIE';b.className='badge '+(bad?'fail':'pass')}$('tolerance').addEventListener('input',updateBadge);
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('saveImageBtn').onclick=()=>rc.toBlob(b=>download(b,`lichtveld_${new Date().toISOString().replace(/[:.]/g,'-')}.png`),'image/png');$('saveCsvBtn').onclick=()=>{if(!analysis)return;const h='timestamp,width_mm,height_mm,left_mm,right_mm,top_mm,bottom_mm,center_x_mm,center_y_mm\n',r=[new Date().toISOString(),analysis.width,analysis.height,analysis.left,analysis.right,analysis.top,analysis.bottom,analysis.cx,analysis.cy].join(',')+'\n';download(new Blob([h+r],{type:'text/csv'}),'lichtveld_meting.csv')};if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
