'use strict';

const A4_W=210, A4_H=297, PPM=3;
const OUT_W=Math.round(A4_W*PPM), OUT_H=Math.round(A4_H*PPM);
const FIELD=100, FX0=(A4_W-FIELD)/2, FY0=(A4_H-FIELD)/2, FX1=FX0+FIELD, FY1=FY0+FIELD;
const REF=[
  {id:0,name:'G / A',x:18,y:18},
  {id:1,name:'G / B',x:192,y:18},
  {id:2,name:'T / B',x:192,y:279},
  {id:3,name:'T / A',x:18,y:279}
];
const APRILTAG_FAMILY='tag36h11';
const APP_VERSION='v7-perspective-apriltag';
const TAGS={"0":[[1,1,1,1,1,1,1,1],[1,1,1,0,1,1,1,1],[1,1,0,0,1,0,1,1],[1,1,1,1,0,1,0,1],[1,1,1,1,0,0,1,1],[1,0,1,0,0,0,1,1],[1,0,1,0,1,0,0,1],[1,1,1,1,1,1,1,1]],"1":[[1,1,1,1,1,1,1,1],[1,0,1,1,0,1,1,1],[1,0,1,0,0,1,0,1],[1,1,1,1,0,0,1,1],[1,1,1,0,0,0,0,1],[1,0,0,0,1,0,1,1],[1,1,0,0,1,0,0,1],[1,1,1,1,1,1,1,1]],"2":[[1,1,1,1,1,1,1,1],[1,1,0,0,0,1,1,1],[1,1,1,0,1,1,1,1],[1,0,1,1,0,1,1,1],[1,1,1,1,1,1,0,1],[1,1,0,1,1,0,1,1],[1,0,0,0,1,0,0,1],[1,1,1,1,1,1,1,1]],"3":[[1,1,1,1,1,1,1,1],[1,1,1,1,0,0,1,1],[1,1,0,1,1,0,0,1],[1,0,1,1,0,1,0,1],[1,0,0,0,1,1,0,1],[1,0,0,0,1,1,1,1],[1,0,1,1,0,0,0,1],[1,1,1,1,1,1,1,1]]};
const $=id=>document.getElementById(id);
const input=$('photoInput'), pc=$('photoCanvas'), rc=$('resultCanvas');
const pctx=pc.getContext('2d',{willReadFrequently:true}), rctx=rc.getContext('2d',{willReadFrequently:true});
let sourceImage=null,points=[],analysis=null;
input.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const bmp=await createImageBitmap(f),s=Math.min(1,2200/Math.max(bmp.width,bmp.height));pc.width=Math.round(bmp.width*s);pc.height=Math.round(bmp.height*s);pctx.drawImage(bmp,0,0,pc.width,pc.height);sourceImage=pctx.getImageData(0,0,pc.width,pc.height);points=[];analysis=null;$('detectionCard').hidden=false;$('resultCard').hidden=true;$('detectStatus').textContent='Vier AprilTags (tag36h11) zoeken...';$('detectionCard').scrollIntoView({behavior:'smooth'});setTimeout(autoDetectAndAnalyze,100)}catch(err){alert('Foto kon niet worden geopend: '+err.message)}});$('retryBtn').onclick=()=>autoDetectAndAnalyze();
function luminance(r,g,b){return .2126*r+.7152*g+.0722*b}
function makeSmall(maxDim=1200){const sc=Math.min(1,maxDim/Math.max(sourceImage.width,sourceImage.height)),w=Math.max(1,Math.round(sourceImage.width*sc)),h=Math.max(1,Math.round(sourceImage.height*sc)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true}),tmp=document.createElement('canvas');tmp.width=sourceImage.width;tmp.height=sourceImage.height;tmp.getContext('2d').putImageData(sourceImage,0,0);x.drawImage(tmp,0,0,w,h);return{img:x.getImageData(0,0,w,h),scale:sourceImage.width/w}}
function components(mask,w,h,minArea,maxArea){const seen=new Uint8Array(w*h),stack=new Int32Array(w*h),out=[];for(let i=0;i<w*h;i++){if(!mask[i]||seen[i])continue;let sp=0;stack[sp++]=i;seen[i]=1;let area=0,minx=w,miny=h,maxx=0,maxy=0,sx=0,sy=0,minSum=1e9,maxSum=-1e9,minDiff=1e9,maxDiff=-1e9,pMinSum=null,pMaxSum=null,pMinDiff=null,pMaxDiff=null;while(sp){const q=stack[--sp],y=(q/w)|0,x=q-y*w;area++;sx+=x;sy+=y;if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y;const sum=x+y,diff=x-y;if(sum<minSum){minSum=sum;pMinSum={x,y}}if(sum>maxSum){maxSum=sum;pMaxSum={x,y}}if(diff<minDiff){minDiff=diff;pMinDiff={x,y}}if(diff>maxDiff){maxDiff=diff;pMaxDiff={x,y}}for(let yy=Math.max(0,y-1);yy<=Math.min(h-1,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(w-1,x+1);xx++){const n=yy*w+xx;if(!seen[n]&&mask[n]){seen[n]=1;stack[sp++]=n}}}if(area>=minArea&&area<=maxArea)out.push({area,minx,miny,maxx,maxy,cx:sx/area,cy:sy/area,quad:[pMinSum,pMaxDiff,pMaxSum,pMinDiff]})}return out}
function rotateGrid(g){const n=g.length,o=Array.from({length:n},()=>Array(n).fill(0));for(let r=0;r<n;r++)for(let c=0;c<n;c++)o[c][n-1-r]=g[r][c];return o}function hamming(a,b){let n=0;for(let r=0;r<a.length;r++)for(let c=0;c<a.length;c++)if(a[r][c]!==b[r][c])n++;return n}
function sampleGrayBilinear(img,x,y){const d=img.data,w=img.width,h=img.height;if(x<0||y<0||x>=w-1||y>=h-1)return 255;const x0=Math.floor(x),y0=Math.floor(y),dx=x-x0,dy=y-y0,g=(xx,yy)=>{const i=(yy*w+xx)*4;return luminance(d[i],d[i+1],d[i+2])};return g(x0,y0)*(1-dx)*(1-dy)+g(x0+1,y0)*dx*(1-dy)+g(x0,y0+1)*(1-dx)*dy+g(x0+1,y0+1)*dx*dy}
function quadMap(quad,u,v){const[tl,tr,br,bl]=quad;return{x:(1-u)*(1-v)*tl.x+u*(1-v)*tr.x+u*v*br.x+(1-u)*v*bl.x,y:(1-u)*(1-v)*tl.y+u*(1-v)*tr.y+u*v*br.y+(1-u)*v*bl.y}}
function otsuThreshold(values){const hist=new Array(256).fill(0);for(const v of values)hist[Math.max(0,Math.min(255,Math.round(v)))]++;const total=values.length;let sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sumB=0,wB=0,best=-1,th=127;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF,between=wB*wF*(mB-mF)*(mB-mF);if(between>best){best=between;th=t}}return th}
function decodeMarker(img,c){const quad=c.quad;if(!quad||quad.some(p=>!p))return null;const top=Math.hypot(quad[1].x-quad[0].x,quad[1].y-quad[0].y),bottom=Math.hypot(quad[2].x-quad[3].x,quad[2].y-quad[3].y),left=Math.hypot(quad[3].x-quad[0].x,quad[3].y-quad[0].y),right=Math.hypot(quad[2].x-quad[1].x,quad[2].y-quad[1].y),mn=Math.min(top,bottom,left,right),mx=Math.max(top,bottom,left,right);if(mn<24||mx/mn>2.4)return null;const vals=[];for(let r=0;r<8;r++)for(let col=0;col<8;col++){const u=(col+.5)/8,v=(r+.5)/8,du=.12/8,dv=.12/8;let sum=0,n=0;for(const[ou,ov]of[[0,0],[-du,0],[du,0],[0,-dv],[0,dv]]){const p=quadMap(quad,u+ou,v+ov);sum+=sampleGrayBilinear(img,p.x,p.y);n++}vals.push(sum/n)}const threshold=otsuThreshold(vals);let grid=Array.from({length:8},(_,r)=>Array.from({length:8},(_,col)=>vals[r*8+col]<threshold?1:0));let border=0,total=0;for(let r=0;r<8;r++)for(let col=0;col<8;col++)if(r===0||r===7||col===0||col===7){total++;border+=grid[r][col]}if(border/total<.74)return null;let best=null;for(let rot=0;rot<4;rot++){for(const[id,ref]of Object.entries(TAGS)){const hd=hamming(grid,ref);if(!best||hd<best.hd)best={id:Number(id),hd,rot}}grid=rotateGrid(grid)}const sorted=[...vals].sort((a,b)=>a-b),contrast=sorted[52]-sorted[12];if(!best||best.hd>5||contrast<18)return null;const center=quadMap(quad,.5,.5);return{id:best.id,hd:best.hd,rotation:best.rot,confidence:(1-best.hd/6)*Math.min(1,contrast/80),cx:center.x,cy:center.y,quad}}
function polygonArea(pts){let s=0;for(let i=0;i<pts.length;i++){const p=pts[i],q=pts[(i+1)%pts.length];s+=p.x*q.y-q.x*p.y}return Math.abs(s)/2}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function detectMarkers(){if(!sourceImage)throw new Error('Geen foto geladen.');const{img,scale}=makeSmall(),w=img.width,h=img.height,d=img.data,N=w*h,sample=[],step=Math.max(1,Math.floor(N/50000));for(let p=0;p<N;p+=step){const i=p*4;sample.push(luminance(d[i],d[i+1],d[i+2]))}sample.sort((a,b)=>a-b);const q10=sample[Math.floor(sample.length*.10)],q50=sample[Math.floor(sample.length*.50)],darkThr=Math.min(125,Math.max(35,q10+(q50-q10)*.45)),dark=new Uint8Array(N);for(let i=0;i<N;i++){const j=i*4;if(luminance(d[j],d[j+1],d[j+2])<darkThr)dark[i]=1}const minSide=Math.min(w,h),cs=components(dark,w,h,Math.max(35,Math.round(N*.000012)),Math.round(N*.035)).filter(c=>{const bw=c.maxx-c.minx+1,bh=c.maxy-c.miny+1,ratio=bw/bh,fill=c.area/(bw*bh);return Math.min(bw,bh)>minSide*.012&&Math.max(bw,bh)<minSide*.28&&ratio>.45&&ratio<2.2&&fill>.08&&fill<.96});const decoded=[];for(const c of cs){const m=decodeMarker(img,c);if(m&&m.confidence>.08)decoded.push(m)}const byId=new Map();for(const m of decoded){const old=byId.get(m.id);if(!old||m.hd<old.hd||(m.hd===old.hd&&m.confidence>old.confidence))byId.set(m.id,m)}const missing=[0,1,2,3].filter(id=>!byId.has(id));if(missing.length){const labels={0:'G/A',1:'G/B',2:'T/B',3:'T/A'};throw new Error('Niet alle vier AprilTags zijn herkend. Ontbrekend: '+missing.map(id=>labels[id]).join(', ')+'. Gebruik referentieblad APRILTAG36H11-V2; zorg dat alle tags volledig zichtbaar zijn, inclusief de witte rand, en vermijd sterke schittering.')}const markers=[0,1,2,3].map(id=>byId.get(id)),pts=markers.map(m=>({x:m.cx*scale,y:m.cy*scale}));if(polygonArea(pts)<sourceImage.width*sourceImage.height*.06)throw new Error('De vier tags vormen een te klein meetvlak. Neem het volledige A4-blad ruimer in beeld.');const top=dist(pts[0],pts[1]),right=dist(pts[1],pts[2]),bottom=dist(pts[2],pts[3]),left=dist(pts[3],pts[0]);if(Math.min(top,right,bottom,left)<40)throw new Error('De markergeometrie is niet betrouwbaar.');return pts}
function drawDetected(){pctx.putImageData(sourceImage,0,0);pctx.lineWidth=Math.max(3,pc.width/450);pctx.font=`bold ${Math.max(17,pc.width/34)}px system-ui`;points.forEach((p,i)=>{pctx.beginPath();pctx.arc(p.x,p.y,Math.max(12,pc.width/90),0,Math.PI*2);pctx.strokeStyle='#00c853';pctx.stroke();pctx.fillStyle='#00a844';pctx.fillText(REF[i].name,p.x+14,p.y-12)});pctx.strokeStyle='#00c853';pctx.beginPath();points.forEach((p,i)=>i?pctx.lineTo(p.x,p.y):pctx.moveTo(p.x,p.y));pctx.closePath();pctx.stroke()}
async function autoDetectAndAnalyze(){if(!sourceImage)return;try{$('detectStatus').textContent='AprilTags G/A, G/B, T/B en T/A zoeken...';await new Promise(r=>setTimeout(r,50));points=detectMarkers();drawDetected();$('detectStatus').textContent='4/4 AprilTags herkend. Perspectief corrigeren en analyseren...';await new Promise(r=>setTimeout(r,70));const rect=rectify();rc.width=OUT_W;rc.height=OUT_H;rctx.putImageData(rect,0,0);analysis=analyzeRect(rect);drawOverlay();showResult();$('detectStatus').textContent='4/4 AprilTags automatisch herkend: G boven, T onder, A links, B rechts.';$('resultCard').hidden=false;$('resultCard').scrollIntoView({behavior:'smooth'})}catch(e){points=[];analysis=null;if(sourceImage)pctx.putImageData(sourceImage,0,0);$('resultCard').hidden=true;$('detectStatus').textContent='Geen geldige automatische kalibratie — meting geblokkeerd.';alert('Analyse gestopt: '+e.message)}}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let m=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[m][k]))m=i;[M[k],M[m]]=[M[m],M[k]];if(Math.abs(M[k][k])<1e-12)throw new Error('Kalibratie is geometrisch instabiel.');const dv=M[k][k];for(let j=k;j<=n;j++)M[k][j]/=dv;for(let i=0;i<n;i++)if(i!==k){const q=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=q*M[k][j]}}return M.map(r=>r[n])}
function homography(dst,src){const A=[],b=[];for(let i=0;i<4;i++){const x=dst[i].x,y=dst[i].y,u=src[i].x,v=src[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}return[...solve(A,b),1]}
function mapH(h,x,y){const d=h[6]*x+h[7]*y+h[8];return{x:(h[0]*x+h[1]*y+h[2])/d,y:(h[3]*x+h[4]*y+h[5])/d}}
function sampleBilinear(data,w,h,x,y){if(x<0||y<0||x>=w-1||y>=h-1)return[255,255,255,255];const x0=Math.floor(x),y0=Math.floor(y),dx=x-x0,dy=y-y0,out=[0,0,0,255];for(let c=0;c<3;c++){const i00=(y0*w+x0)*4+c,i10=i00+4,i01=i00+w*4,i11=i01+4;out[c]=data[i00]*(1-dx)*(1-dy)+data[i10]*dx*(1-dy)+data[i01]*(1-dx)*dy+data[i11]*dx*dy}return out}
function rectify(){const dst=REF.map(p=>({x:p.x*PPM,y:p.y*PPM})),h=homography(dst,points),out=new ImageData(OUT_W,OUT_H),sd=sourceImage.data;for(let y=0;y<OUT_H;y++)for(let x=0;x<OUT_W;x++){const s=mapH(h,x,y),rgba=sampleBilinear(sd,sourceImage.width,sourceImage.height,s.x,s.y),i=(y*OUT_W+x)*4;out.data[i]=rgba[0];out.data[i+1]=rgba[1];out.data[i+2]=rgba[2];out.data[i+3]=255}return out}
function grayAt(d,i){return .2126*d[i]+.7152*d[i+1]+.0722*d[i+2]}function smooth(a,r=8){const out=new Float32Array(a.length),p=new Float64Array(a.length+1);for(let i=0;i<a.length;i++)p[i+1]=p[i]+a[i];for(let i=0;i<a.length;i++){const lo=Math.max(0,i-r),hi=Math.min(a.length,i+r+1);out[i]=(p[hi]-p[lo])/(hi-lo)}return out}
function profile(img,axis,x0,y0,x1,y1){const d=img.data,w=img.width;if(axis==='x'){const a=new Float32Array(x1-x0);for(let x=x0;x<x1;x++){const v=[];for(let y=y0;y<y1;y+=3)v.push(grayAt(d,(y*w+x)*4));v.sort((a,b)=>a-b);a[x-x0]=v[Math.floor(v.length/2)]}return smooth(a)}const a=new Float32Array(y1-y0);for(let y=y0;y<y1;y++){const v=[];for(let x=x0;x<x1;x+=3)v.push(grayAt(d,(y*w+x)*4));v.sort((a,b)=>a-b);a[y-y0]=v[Math.floor(v.length/2)]}return smooth(a)}
function derivative(a){const d=new Float32Array(a.length);for(let i=1;i<a.length-1;i++)d[i]=(a[i+1]-a[i-1])/2;return d}function peakAbs(d,e,s){let lo=Math.max(1,Math.round(e-s)),hi=Math.min(d.length-2,Math.round(e+s)),best=lo,bv=-1;for(let i=lo;i<=hi;i++){const v=Math.abs(d[i]);if(v>bv){bv=v;best=i}}return{idx:best,strength:bv}}
function analyzeRect(img){const m=25,x0=Math.round((FX0-m)*PPM),x1=Math.round((FX1+m)*PPM),y0=Math.round((FY0-m)*PPM),y1=Math.round((FY1+m)*PPM),cp=derivative(profile(img,'x',x0,y0,x1,y1)),rp=derivative(profile(img,'y',x0,y0,x1,y1)),s=30*PPM,L=peakAbs(cp,m*PPM,s),R=peakAbs(cp,(m+100)*PPM,s),G=peakAbs(rp,m*PPM,s),T=peakAbs(rp,(m+100)*PPM,s),Xl=x0+L.idx,Xr=x0+R.idx,Yg=y0+G.idx,Yt=y0+T.idx,width=(Xr-Xl)/PPM,height=(Yt-Yg)/PPM;if(width<60||width>140||height<60||height>140)throw new Error(`Onwaarschijnlijke veldmaat gevonden (${width.toFixed(1)} x ${height.toFixed(1)} mm).`);return{width,height,left:Xl/PPM-FX0,right:Xr/PPM-FX1,top:Yg/PPM-FY0,bottom:Yt/PPM-FY1,cx:(Xl+Xr)/(2*PPM)-A4_W/2,cy:(Yg+Yt)/(2*PPM)-A4_H/2,bounds:[Xl,Yg,Xr,Yt]}}
function drawOverlay(){const[xl,yg,xr,yt]=analysis.bounds;rctx.lineWidth=3;rctx.strokeStyle='#222';rctx.strokeRect(FX0*PPM,FY0*PPM,100*PPM,100*PPM);rctx.strokeStyle='#ff2424';rctx.strokeRect(xl,yg,xr-xl,yt-yg);rctx.strokeStyle='#1769ff';rctx.beginPath();rctx.moveTo(OUT_W/2-18,OUT_H/2);rctx.lineTo(OUT_W/2+18,OUT_H/2);rctx.moveTo(OUT_W/2,OUT_H/2-18);rctx.lineTo(OUT_W/2,OUT_H/2+18);rctx.stroke()}
function mm(v){return`${v>=0?'+':''}${v.toFixed(2)} mm`}function showResult(){$('widthOut').textContent=analysis.width.toFixed(2)+' mm';$('heightOut').textContent=analysis.height.toFixed(2)+' mm';$('leftOut').textContent=mm(analysis.left);$('rightOut').textContent=mm(analysis.right);$('topOut').textContent=mm(analysis.top);$('bottomOut').textContent=mm(analysis.bottom);$('cxOut').textContent=mm(analysis.cx);$('cyOut').textContent=mm(analysis.cy);updateBadge()}
function updateBadge(){if(!analysis)return;const t=parseFloat($('tolerance').value),bad=[analysis.left,analysis.right,analysis.top,analysis.bottom].some(v=>Math.abs(v)>t),b=$('statusBadge');b.textContent=bad?'BUITEN INGESTELDE TOLERANTIE':'BINNEN INGESTELDE TOLERANTIE';b.className='badge '+(bad?'fail':'pass')}$('tolerance').addEventListener('input',updateBadge);
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('saveImageBtn').onclick=()=>rc.toBlob(b=>download(b,`lichtveld_${new Date().toISOString().replace(/[:.]/g,'-')}.png`),'image/png');$('saveCsvBtn').onclick=()=>{if(!analysis)return;const h='timestamp,width_mm,height_mm,A_left_mm,B_right_mm,G_top_mm,T_bottom_mm,center_x_mm,center_y_mm\n',r=[new Date().toISOString(),analysis.width,analysis.height,analysis.left,analysis.right,analysis.top,analysis.bottom,analysis.cx,analysis.cy].join(',')+'\n';download(new Blob([h+r],{type:'text/csv'}),'lichtveld_meting.csv')};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=7').catch(()=>{});
